name: Build-Docker-Image-Workflow

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
#    if: contains(github.event.head_commit.message, '[docker to ecr]')
    steps:

#      - name: Checkout repository
#        uses: actions/checkout@v2 #DELETE LATER
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: test-codebuild
          buildspec-override: .github/workflows/buildspec.yml
          env-vars-for-codebuild: |
#            AWS_DEFAULT_REGION,
#            AWS_ACCOUNT_ID,
#            IMAGE_REPO_NAME,
#            IMAGE_TAG
#        env:
#          AWS_DEFAULT_REGION: us-east-2
#          AWS_ACCOUNT_ID: 505625506668 #ASK RACHAEL IF THIS GOES IN SECRETS
#          IMAGE_REPO_NAME: testing-gh-actions
#          IMAGE_TAG: $ {{ github.sha }}
          #role-name = codebuild-test-codebuild-gh-actions-service-role
          ##


